### ISSUE TITLE
Support for GPT 4

### ISSUE THREAD

**Issue by souvikmaji** [OpenPluginACI/openplugin#36]
**Is your feature request related to a problem? Please describe.**
Is there a plan to support gpt 4?

**Describe the solution you'd like**
I use gpt API keys to access gpt4, there can be an option to change the model version and another option to set gpt API keys. 

**Describe alternatives you've considered**
The other alternative is to have a paid version of the app, which can use GPT 4. 
I prefer to have the option to set my own API keys, in that way, I can avoid having multiple subscriptions to use gpt4.

**Comment by CakeCrusher** [comment]
@souvikmaji In openplugin.io the ability to input your own keys and to use GPT 4 is already available. Is this what you are looking for?
![image](https://github.com/OpenPluginACI/openplugin/assets/37946988/d16386d8-d017-4795-bcc0-8853e15e2e3c)
![image](https://github.com/OpenPluginACI/openplugin/assets/37946988/ce297692-8fc4-4d03-8fac-194118e198d2)

**Comment by souvikmaji** [comment]
yes, this is it. thanks a lot
